// Team types
export interface Team {
  number: string;
  name: string;
}

// Match types
export interface MatchData {
  id?: number; // Auto-generated by IndexedDB
  teamNumber: string;
  teamName: string;
  tournamentStage: TournamentStage;
  matchNumber: number;
  allianceColor: 'Red' | 'Blue';
  performanceRatings: PerformanceRatings;
  climbing: ClimbingType;
  overallImpression: number;
  comments: string;
  timestamp: number; // Unix timestamp
}

export type TournamentStage = 'Qualifications' | 'Quarterfinals' | 'Semifinals' | 'Finals';
export type ClimbingType = 'None' | 'Low' | 'High';

export interface PerformanceRatings {
  defensePerformance: Rating;
  avoidingDefense: Rating;
  scoringAlgae: Rating;
  scoringCorals: Rating;
  autonomous: Rating;
  drivingSkill: Rating;
}

export interface Rating {
  score: number; // 1-7 rating
  notes?: string; // Optional notes
}

// Team Averages
export interface TeamAverages {
  teamNumber: string;
  teamName: string;
  matchCount: number;
  defensePerformance: number;
  avoidingDefense: number;
  scoringAlgae: number;
  scoringCorals: number;
  autonomous: number;
  drivingSkill: number;
  overallImpression: number;
  climbingCounts: {
    None: number;
    Low: number;
    High: number;
  };
}

// Filter types
export interface TeamDataFilter {
  tournamentStage?: TournamentStage | 'All';
  climbing?: ClimbingType | 'All';
  minOverallScore?: number;
}

// Export/Import types
export interface ExportData {
  version: string;
  exportDate: number;
  matches: MatchData[];
}

export interface DataStats {
  teamsCount: number;
  matchesCount: number;
  dataSize: string;
  lastSync?: number;
}

// Pre-defined teams list
export const TEAMS: Team[] = [
  { number: "1574", name: "Miscar" },
  { number: "1577", name: "Steampunk" },
  { number: "1690", name: "Orbit" },
  { number: "1937", name: "RoboActive" },
  { number: "1942", name: "Elysium" },
  { number: "2096", name: "Cinderella" },
  { number: "2230", name: "General Angels" },
  { number: "2231", name: "OnyxTronix" },
  { number: "3065", name: "Jatt" },
  { number: "3075", name: "Ha-Dream Team" },
  { number: "3083", name: "Artemis" },
  { number: "3211", name: "The Y Team" },
  { number: "3316", name: "D-Bug" },
  { number: "3339", name: "BumbleB" },
  { number: "3388", name: "Flash" },
  { number: "4320", name: "The Joker" },
  { number: "4338", name: "Falcons" },
  { number: "4416", name: "Skynet" },
  { number: "4586", name: "PRIMO" },
  { number: "4590", name: "GreenBlitz" },
  { number: "4661", name: "Cypher" },
  { number: "4744", name: "Ninjas" },
  { number: "5135", name: "Black Unicorns" },
  { number: "5554", name: "The Poros Robot"}
];
